Es un retrete sencillo y elegante...
¿Quieres inspeccionarlo?
***Deja que piense... NO
    Lo siento, no es nada personal...
***¡Ni por todo el oro del mundo!
    Lo siento, no es nada personal...
***Me niego rotundamente
    Lo siento, no es nada personal...
***¡¡PUAJ!! ¡Ni se te ocurra!
    Lo siento, no es nada personal...